### ISSUE TITLE
Cannot Add New Record to the Issues database

### ISSUE THREAD

**Issue by ellenculp** [CIMDBORG/CIMMigrationProject#39]
Message appears 'Fields Marked with an * Must Be Filled'.  Click Ok, then a box with 'System.Data.SQLClient.SQL exception (0x80131904)
FYI I could not attach the screen prints in GitHub

**Comment by mikey2695** [comment]
Ellen,

I know someone else who ran into this problem who just didn't have the application updated.

Open the database from the LAN (double-click the circled below):

![image](https://user-images.githubusercontent.com/52287707/74256105-e35a5000-4cc0-11ea-9faa-6db57d6cbdcc.png)

Let us know if you are still running into the error after that.

**Comment by mikey2695** [comment]
This seems to have been fixed, someone please verify

**Comment by brcox90** [comment]
I've added a couple issues today. Fine on my end.

**Comment by mikey2695** [comment]
This was the old issue @NickD0w raised the other day about not being able to add issues with a planned date. Make sure we can add issues with a planned date

**Comment by ellenculp** [comment]
I am still not able to add issues even entering the issues db from the LAN

Ellen Culp
UPS Customer and Billing
201-828-7829
5-283-7829
eculp@ups.com<mailto:eculp@ups.com>

Confidentiality Notice: This message is intended exclusively for the individual or entity to which it is addressed. This communication may contain information that is proprietary, privileged, confidential or otherwise legally exempt from disclosure. If you are not the named addressee, you are not authorized to read, print, retain, copy or disseminate this message or any part of it. If you have received this message in error, please notify the sender immediately either by phone (201-828-7829) or reply to this e-mail and delete all copies of this message

**Comment by brcox90** [comment]
@mikey2695 someone's most likely going to have to sit with Ellen and trouble shoot this one.

**Comment by mikey2695** [comment]
@brcox90 @ellenculp I ran it in the test environment without a problem, once we do our final push this should be good. 
Ellen, the change hasn't been put through yet, which is why you still have the error

**Comment by brcox90** [comment]
Fixed in last update
